# Generated by Django 2.0.5 on 2018-11-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter book genre', max_length=200)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
    ]
